id: P000345
initial_creation_type: ocr
created_at: 14/03/2020
last_modified_at: 2021-12-16 15:35:07.520579
source_metadata:
  id: bdr:W21884
  title: འབྲུ་འགྲེལ་འཕྲུལ་ལྡེའི་གསལ་འགྲེལ་ཐུ་མིའི་དགོངས་གནད་གསལ་བའི་མེ་ལོང་།
  author: ''
  volumes:
    4d1060e8a904462795f570a2b264c6a9:
      image_group_id: I1KG14895
      title: Volume 1 of 'bru 'grel 'phrul lde'i gsal 'grel thu mi'i dgongs gnad gsal
        ba'i me long
      volume_number: 1
      total_pages: 228
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
